### ISSUE TITLE
Cuckoo filter in design 2: In section 'Scalability': Where do the 110MB come from?

### ISSUE THREAD

**Issue by dan-blank** [DP-3T/documents#158]
Unfortunaly I fail to reproduce this number on my own, most likely because I have some misunderstanding on my part. Could someone check my calculation please? These are my assumptions so far:

- The complete cuckoo filter is 110MB and contains all seeds that created EphIDs during the infectious windows

- (1) Assuming a constant rate of 40k new infections per day and an epoch length of 1 day, there is the following upper bound of seeds to be stored (lets assume for simplicity that no seed gets deleted): 40000 infected persons create 14 seeds. 40000 * 14 new seeds get added each day for the last two weeks. So in total, the cuckoo filter needs to store 40000 * 14 * 14 = 7840000 seeds.

- (2) Assuming a FPP (false positive rate) of 1 in a million, that is p = 0.000001.

- (3) Assuming that a new cuckoo filter is created every 4 hours, so per day, 6 different cuckoo filters have to be downloaded.

According to https://brilliant.org/wiki/cuckoo-filter/, the amount of bits needed to store one entry can be calculated by: (log(1 / p) + 2) / L, where p is the FPP and L is the load of the cuckoo filter. If we use (2) and assume L = .955, then we get (log(1 / 0.000001) + 2) / 0.955 = 8.37 bits per entry. We have 7840000 entries, so that is 65620800 bits used by one cuckoo filter. A user needs to download 6 of those daily (3), so they need to download 393724800 or 49MB daily, and that is a very conservative upper bound (b.c. not deleting seeds).

Is my calculation correct? Most likely I have the wrong p-value, but I would be grateful for any mistake found. Thank you for your time!

**Comment by a8x9** [comment]
- You need to store the EphID in the cuckoo filter, not the seed. Contacts have the EphID to compare against the filter, they don't know the seed from which they were derived.

- You should only include the infections reported during the last 24 hours in your filter (assuming you generate one filter per day). Re-including entries which were already present in a previously generated filter is a waste of bandwidth.

- You used log<sub>10</sub> instead of log<sub>2</sub>

The white paper lacks a lot of details regarding how they computed these numbers. The don't define:
- the used epoch value
- target false positive rate

However, they mention that they assume a 5 days contagious window.

So if we assume:
- contagious window: 5 days
- epoch: 15 min.
- reported infections per day: 40,000
- B = bits per entry

B = (110,000,000 * 8) / (40,000 * 5 * 24 * 4) ~= 45.83
**p** = 1 / 2 ^ (L * B - 2) = 1 / 2 ^ (0.955 * 45.83 - 2) ~= **2.67e-13**

**Comment by dan-blank** [comment]
@a8x9 Thank you, that already helped a great deal :)

I re-read the whitepaper and am now convinced of what you say. Originally, I was thrown off by question 6 in the faq: https://github.com/DP-3T/documents/blob/master/FAQ.md#p6-why-do-infected-people-upload-a-seed-which-enables-recreating-ephids-instead-of-their-individual-ephids-

In particular because by the passage 

> For comparison, sending 21 days of EphIDs rotated every 15 minutes requires sending 32kB per infected patient. Even when compressing these EphIDs in a cuckoo filter, we’d need around 8kB per infected patient. So smartphones would need to download at least 2 orders of magnitude more (e.g., for 30k infected a day: from around 1 MB to 230 MB per day).

This implies that there are more EphIDs than seeds. However, the seeds themselves are not being stored in the table, since a cuckoo filter stores only the hashes of the seeds. At least that is how I understood it: Due to storage consideration, we store the seeds instead of

**Comment by a8x9** [comment]
I was also a bit confused about how frequently seeds change in *design 2*, see the edit on my above response.

P6 in the FAQ is about *design 1*. I think that when they wrote it, *design 2* was not existing yet. What they call *seed* in the FAQ is not the seed<sub>i</sub> from *design 2* in the whitepaper, but is the SK<sub>t</sub> from *design 1*.
