### ISSUE TITLE
ECDH to generate EphIDs

### ISSUE THREAD

**Issue by tree-go** [DP-3T/documents#159]
- every device advertises the public key (it is 32-byte, maybe need 2 advertisements)
- when a device gets another device's public key by ble scanning, do ECDH, and keeps the ECDH result. so for a same advertisement, different scanners will get different "result"; and for a non-advertising scanner, it won't get any ECDH result.
- when a user is confirmed infected, uploads the ECDH results.

this approach is similar as solution#2, but for the infected users, they have the option to filter some ECDH results; and different scanners get different "scan results" for the same advertisement.

**Comment by a8x9** [comment]
I've propose this improvement in #66, and @colmmacc later proposed the same idea in #87.

This solution solves most problems related to deanonymization of infected users caused by BLE traffic recording. It also solves most problems related to replay attacks.

Unfortunately, the  DP^3T team seems to completely ignore any external suggestion.

But in the end that probably won't matter. Google and Apple have announced their protocol which is very similar and with the same drawbacks as the DP^3T ones. So in the best case scenario, all contact tracing apps not using their API won't be able to use Bluetooth in the background (at least on iOS), as it is already the case. In the worst case scenario, all contact tracing apps not using their API will just be banned from their app stores. Yay...

**Comment by kennypaterson** [comment]
Sorry, we are inundated with feedback on the proposal, and we are triaging. We have considered exactly this proposal internally and decided not to adopt it for 2 reasons: added complexity (need to send and capture multiple beacons in order to assemble an ECDH value) and limited benefit. The latest version of the whitepaper contains an alternative countermeasure based on secret sharing.

**Comment by cascremers** [comment]
Hi, just to add that we are absolutely not ignoring external suggestions, and many suggestions have already been included.

The team is working extremely hard on a range of aspects, dealing with a huge number of communications, and parts of the design that we like to further specify. We therefore have to prioritize things, as Kenny points out. We would love to be able to address each individual suggestion independently, but this is unfortunately not yet possible. 

We appreciate your patience and understanding.

**Comment by cascremers** [comment]
Hi, now revisiting this question, this seems to be answered in the second paragraph of [this FAQ entry](https://github.com/DP-3T/documents/blob/master/FAQ.md#p4-why-is-the-system-not-using-public-key-cryptography-when-broadcasting-identifiers).

**Comment by a8x9** [comment]
If you read my proposal in #66, it does not require multiple packets (advertising packets stays the same during a whole epoch), and it does not require establishing connections (just using the advertisement packets). So still N broadcasts and not N^2.

**Comment by galadran** [comment]
Hi a8x9, I've replied to your issue directly.

**Comment by tree-go** [comment]
we can close this issue, and keep the discussing on  #66.
