### ISSUE TITLE
Non sequential storage of ephid

### ISSUE THREAD

**Issue by gscokart** [DP-3T/documents#18]
It is maybe obvious, but I don't see it mentioned.

The local storage for the collected ephid should not be sequential or use a structure from which you can derive the sequence of insertion.

That would reduce the possibility to drill down the time of infection to a finer level.

**Comment by jasisz** [comment]
Leaving it sequential leaves opportunity to inform second level of encounters on some basis.

And it does not give much, as malicious user still can store it sequentially.

**Comment by gscokart** [comment]
You can still keep sequence in memory for a short period.

For the malicious user, that would still protect against a user installing a second app that could exploit the data a posteriori (for instance when the person learn that he is at risk or even is infected).

**Comment by jasisz** [comment]
But this data is sequential by nature. If someone wants to drill down the time of infection, it is as simple as storing ephids on your own.

**Comment by s-chtl** [comment]
Hi @gscokart , thanks for raising the issue.
Indeed, it is a very good point and something that developers should pay attention to because it has important privacy implications. We cannot currently definitely answer this as it is an implementation specific question, but, there's no reason to store them sequentially because only the day matters.
I’m flagging the issue to the team working on the reference implementation to make sure that we get the best privacy possible.
Thanks
