### ISSUE TITLE
How to mitigate the risk of gamification

### ISSUE THREAD

**Issue by gscokart** [DP-3T/documents#19]
Is there a risk that stupid people start to play with the app making, trying to be the first one reported at risk?

(I have no knowledge in sociology, to say if it is a real risk nor how to mitigate.  Maybe using a boring interface and avoid visible ranking).

**Comment by maskeeter** [comment]
@gscokart an Authorization from a health authorities should stop that from happening, it could be a non-personalized digital certificate the user receives from health authorities (without them having to know the EphID of user) and then the user himself upload it on infection report. 

But in any case, the user should be able to prove they tested positive in some way or otherwise anyone is able to spoof the system and trigger false notifications without a legal binding causing panic and eventually reducing the trust in the system.

**Comment by gscokart** [comment]
This is after the person is tested.

My concern is more about some stupid person that make a stupid competition to be the first one declared at risk by the application.
They could use the application as an arbitrator for their morbid competition.

**Comment by s-chtl** [comment]
Hi @gscokart, thanks for your input.
Indeed, those are valid points but they seem to be inherent to any system. By design a solution that informs the user whether they are at risk give them the ability to turn it into a game. 
We are hopeful that people will take contact tracing seriously given the lethality of COVID.
