### ISSUE TITLE
Use of TEEs

### ISSUE THREAD

**Issue by muehlber** [DP-3T/documents#25]
The TEE mitigation (https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf,  https://github.com/DP-3T/documents/commit/6ac18840fce3dd1c5e8f101dda7f036cffcbccee, p.15) is not really motivated. TEEs would only make sense if used in a way where the backend would only communicated SKt to a user iff their app is  attested to run in a TEE. However, this would break other properties of your approach as the attestation step would uniquely bind an app instance to a specific mobile device.

The White Paper seems to imply that TEEs offer merely an additional level of isolation. Whether this is true depends on the deployment scenario. In the context of TrustZone on mobile phones, for example, the TEE may be shared. The means to verify that part of an app actually executes under the TEE's protection primitives, is through attestation. Attestation effectively breaks anonymity, unless there's a trusted third party involved.

My intuition is that Trusted Computing can probably help to harden your system against a number of strong adversaries, but it won't be by means of some quick of-the-shelf "let's stick it into an enclave" approach.

**Comment by kennypaterson** [comment]
Thanks, this comment is much appreciated, and we will take it into account in our further considerations.

**Comment by fynngodau** [comment]
I am not sure whether I understood @muehlber's comments on attestation correctly, and as such, am not sure what such an attestation would look like for a TEE. I would imagine it to be similar to Google SafteyNet attestation.

> While it is not impossible to leak this information, it is unlikely.

(Whitepaper page 26)

No matter how good this attestation process is – Google's is complicated, but it can be circumvented –, it is enough if *one single user* decides to trick the server into giving them the data (`SKt`s) directly or otherwise circumvents the TEE to extract data if they decide to publish it elsewhere. Therefore, once one singe TEE is vulnerable, all the data can be extracted. As such, I believe implementing such an obfuscation measure will only hinder independent implementations without providing any benefit in protection against the tech-savy attacker.
