### ISSUE TITLE
aggregated mobility data

### ISSUE THREAD

**Issue by ekg** [DP-3T/documents#30]
A differentially private mobility data set could be used by epidemiologists to help organize responses to ongoing outbreaks or flareups during long-term suppression of the pandemic.

How would this fit into the proposed plan?

It could be collected in parallel, using data directly provided by telcos. In most implementations, a trusted party is needed to generate the DP model. The resulting data could be made public without risk to individuals, and without risk to groups below a certain size, depending on how it is built.

**Comment by mex2meou** [comment]
Hi @ekg, thanks for your suggestion!

Indeed, differentially private mobility datasets could be useful to health authorities and epidemiologists so that they can organize their response to ongoing outbreaks.

Please note that the aim of our project is to enable proximity tracing without collecting or processing any location/mobility data. As such, such an extension falls out of the scope of our current work.
