### ISSUE TITLE
Clarify how to ensure authenticity of Sks marked as infected

### ISSUE THREAD

**Issue by kugelfish42** [DP-3T/documents#58]
The document does not go into much details how authenticity of positively diagnosed Sks would be ensured across the global network of backends and clients. 

- Who can generate tokens to authorize the upload of a key to a backend? Any health authority, any testing center, any doctors office? 
- Could a rogue backend flood the global network with fake IDs? 
- What is the potential harm of a rogue actor who has a legitimate authorization key? 
  - Can they guess many Sks, cause denial of service on the backend distribution? 
  - Phish users into uploading their Sks? 
  - Operate a network of high-powered bluetooth transmitters to widely disseminate EIDs that are later marked fraudulently marked as infected?

What would be the details of the patient worklfow? When would the upload be initiated - when the patient appears at a facility for taking the testing samples, when they get the results (maybe by phone or mail) or through some other way?

**Comment by pevab** [comment]
I agree with the issue.

Clearly, the entities generating "tokens" to authorize upload of a key to a backend must be trusted.

But we could want to minimize data exposure on this part too.

IRMA, by Privacy by Design, offers an Idemix-based approach that might be interesting. See <https://privacybydesign.foundation/irma-en/>

In short:
* Health Authority (HA) is seen as an Issuer that produces "Infected" attributes.
* The patient can request HA for such an attribute. There goes passing the medical test and so on.
* Once endowed with this attribute, the patient can decide to reveal it to the backend server.

IRMA (or other Idemix-based protocol) ensures that:
* HA cannot trace the usage of this attribute, even if HA colludes with the backend server.
* Everyone to which the user has decided to disclose the attribute can verify that it has really been issued by HA.
* No one can issue attribute in the name of HA, except HA.

This requires HA to be a trusted 3rd party. This also requires great care on how the attribute is actually issued to the user.

**Comment by lbarman** [comment]
Hi @kugelfish42, @pevab; thanks for your inputs. Sorry for the long delay. This part isn't fully specified yet, hence I'll merge this to the pinned thread https://github.com/DP-3T/documents/issues/206 so we have everything in one place.

> Who can generate tokens to authorize the upload of a key to a backend? Any health authority, any testing center, any doctors office?

Indeed, this is not well specified yet.

> Could a rogue backend flood the global network with fake IDs?

Yes (we note that clients *locally* compute their matches, so the server cannot trigger at-risk notifications for specific people - it would have to guess which EphIDs a specific person has seen). But it could send all valid EphIDs so that everyone gets an at-risk notification.

> What is the potential harm of a rogue actor who has a legitimate authorization key?

I partially answered this above, let me know.

> Can they guess many Sks, cause denial of service on the backend distribution?

All SKs are valid (chosen at random), so I am not sure about the guessing part ?

> Phish users into uploading their Sks?

Yes, that could be a consequence of the large-scale attack "broadcast all possible EphIDs" above

> Operate a network of high-powered bluetooth transmitters to widely disseminate EIDs that are later marked fraudulently marked as infected?

Yes, this is a possible attack (which if I recall correctly is acknowledged in the paper).

Let me know if this answers the question!

@pevab Thanks for the input, I added it to the discussion on the other thread.
