### ISSUE TITLE
Beacon info relaying (Denial of service)

### ISSUE THREAD

**Issue by jorants** [DP-3T/documents#74]
A malicious user could write an app that sniffs all EphIDs it sees and constantly rotates trough sending a copy of the once seen today. This would create a possible DOS attack against the distributed data, making it seems like there was contact with many people, even when there was none. 

Users of the malicious app could even share the EphIDs, so the attack could be done on a national scale with very few people. If only a few of the EphIDs of infected people are present, then this could lead to many false positives.

In general it is quite easy to copy a beacon ID, see for example the beacon simulator app (https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=nl) in the google play store.

**Comment by mrseeker** [comment]
Another DoS would be using the seeds from known infected people to broadcast new EphIDs. This could be mitigated by timestamping the seeds with a revocation timestamp.

**Comment by lbarman** [comment]
Hi @jorants , thanks; I think our new section 4 of the whitepaper (page 19) partially addresses exactly this problem. In short: secret-share the EphIDs so that eavesdropping/replay attacks/wardriving cannot be done "instantly" but need a minimum capture duration per person.

@mrseeker yes; we are aware of these replay attacks, one possible solution (as you mention) being to have the EphIDs only be valid for a limited period (e.g., by having a timestamp in in their generation). This is currently being investigated.

Would this answer the question ?

**Comment by mrseeker** [comment]
@lbarman Making it valid for a period of time or signing it with a "revocation timestamp" would certainly mitigate the issue.
