### ISSUE TITLE
Blockchain as decentralised storage?

### ISSUE THREAD

**Issue by szetaa** [DP-3T/documents#83]
One thought:
Instead of a central server (we may end up with one per country), was it considered whether Blockchain is fit for purpose to store and distribute the SK_t of confirmed infections?

- Create a global new instance based e.g. on the Ethereum technology (a new COVID-19 coin)
- Every app user has a "wallet"
- Smart contracts can be defined to model and flip attributes like:
	- Shows symptoms / self-quarantine (low quality signal as unverified, but still good for trends)
	- Tested positively (when?) (digitally signed by a testing laboratory to avoid fake alarm chains)
	- Tested for antibodies (considered immune, digitally signed by testing laboratory)

The app can at one point also be used by authorities also to orchestrate waves of lockdown-releases (slices of society get time-windows allocated to move freely, or permanent once tested for antibodies).
This could replace the self-printed forms as carried today in Italy.

Best regards
Ralph

**Comment by mrseeker** [comment]
Blockchain is basically an "open ledger". This means that every entry into the blockchain needs to be validated by the whole chain, which might take hours depending on the amount of "validators". Secondly, it relies on the "Byzantine generals problem", which is basically not needed: Only authorized personnel needs the ability to add/edit the chain, not everyone. This alone already makes blockchain not feasible for a use-case like this. It's easier just to make a public list of infected people than having a huge overhead for "validation" purposes.

Having said that, if you want to have some form of "blockchain" you might also be able to digitally "sign" the previous list with a state-owned digital signature and work from there. This would basically make it a "blockchain", but would also cause the risk that the longer the chain becomes, the more resources it would require to validate all signatures.

**Comment by jorants** [comment]
Some for of distribution could maybe be achieved by using distributes hash tables, allowing trusted NGO's for example to run a server as well. This would mean a centralized attack would require more people to be involved. Plus, there might be a nice bonus when it comes to distributing network load.

**Comment by szetaa** [comment]
I was bringing up the topic of blockchain not with the intent to mirror a distributed ledger, but to use smart contracts as a communication bus to report positive tests globally (and traceable to the testing laboratory).

Therefore many concerns outlined above would not apply (e.g. no need for mining as proof of work / byzantine generals problem). Instead a scenario using Proof of Stake (where only authorised testing institution have a stake / key to execute the contract of publishing a postive test). Or even something like in the Ripple network with backend (but collaborating servers across the _same_ chain).

When reading the whitepaper and commentary, there is a lot of focus on the application and details on its implementation (which is key, because a novum). But I am concerned to read very little on a data storage strategy.

So if not agreed now we may end up with regional silos and just postpone the problems which arise once we need to synchornize the clusters (level of trust, differences in data models, interfaces, p2p or one centralized global instance - owned & run by whom?)

**Comment by FroehlichMarcel** [comment]
@jorants See new paper from Humboldt Univ. Berlin on using DHT:
https://eprint.iacr.org/2020/398

**Comment by mrseeker** [comment]
@szetaa when you say "proof of stake", you basically saying that only a health official (the stake) is allowed to update the database. That is quite similar to a website with a lot of mirrors, no?
What you get is that every health official can send his "work" to the chain, and someone from that chain validates the work and publishes it (the stake). Then everyone gets a copy of that chain and the whole process starts again. It's easier to send all tests with the seed to a health official, who then verifies the claim (who sent the report and is it a good report) and then publishes a list of seeds which he validates to be good. The seed should then revoke itself if it's made public (to prevent collisions) and as long as the seed is not known by health authorities, you can make it completely anonymous.

**Comment by MarkusTeufelberger** [comment]
About the title of this issue: Blockchain is a very centralized storage (there is only one single globally distributed chain/database, not a different one on every device), just with decentralized write access.

There could very well be applications for it to replace some components in the design here, I personally would rather focus on data portability and open access as well as enforcing standards so someone who wants to build a more distributed solution (using blockchain or not) can realistically do it instead of being faced with a lot of locked up data silos.

**Comment by lbarman** [comment]
Thank you all for your inputs!

Using a blockchain as a storage would somewhat increase reliability (with could be addressed much more efficiently with replication) and preventing malicious modifications (but it's not clear what the gain would be there). Smart contract could (perhaps) be used to build a contact-tracing system, but it is again unclear what this additional complexity would bring. Such solution incur large costs in complexity and deployability, as well as adding a whole ecosystem to the security/privacy analysis. We wish to keep it simple :)

This thread also discusses (using blockchains for) data portability and interoperability; while I'm not sure how blockchains helps for this (in comparison with having an open standard), interoperability is a valid concern on which we are working.

Would this answer the question?

**Comment by szetaa** [comment]
Yes please close. I agree with your summary. 
Keep it simple but design to allow a global master-list.

**Comment by Eric1212** [comment]
I know i'm kind of offtopic and posting on a closed topic but i'm wondering if we doesn't need IPFS on this issue ?

https://ipfs.io/

**Comment by MarkusTeufelberger** [comment]
There are no large data sets that are long-term stable, so I am unsure what problem you are planning to solve with IPFS or where it would help?

It is a nice technology and a nice buzzword to drop, but I'd like to see further elaboration than a link to a website and some "wondering" to comment.

**Comment by kollokollo** [comment]
There is probably something to learn from Bitcoin: It is a Peer-to-Peer-Network. So it does not rely on a specific network infrastructure, it just needs a transport medium. 
For the contact tracing app that could mean, that no internet-connection would be needed and the data which should be obtained from the official server would be routed from device to device via -- e.g. bluetooth. But one would need to consider the propagation time in this case, since a contact would be necessary to to transmit any kind of data. For Bitcoin this global propagation usually takes 10 Seconds to 1 minute, but there nearly all devices have (direct) internet access.
This way also a central server (which holds the contact tokens of infected devices) could be obsolete. But to ensure the integrety of the (the distributed) database, a trust mechanism would be necessary. Bitcoin solves this involving big and energy consuming machinery to do proof-of-work, so nobody can in fact alter the content of the database. This is of course totally out of question for an App on a Smartphone. Also one would need incentives for compensation of the energy consumption. In Bitcoin this is easy, the station which do the ensuring work just get some coins. You see: Blockchain alone will acomplish nothing. At least nothing which I can imagine at the moment. So a conventional database will do. This has to be synced to every Smartphone (now done by downloading it from a server), and authenticated by an organization (public health organization) (which could have signed it cryptographically). Thats what DP-3T is about.
