### ISSUE TITLE
Practical - are health authorities able to issue the authorization codes, right now?

### ISSUE THREAD

**Issue by davidbarnardwills** [DP-3T/documents#90]
As a practical question (which I can't answer), are the health authorities who would be conducting the diagnosis currently able to issue the required authorisation codes? 

Is it a fairly trivial thing? is it something that can be done within existing patient records/management systems, or in locked down IT environments, and by staff who are currently overloaded?

If not, what sort of scale/effort of deployment would be necessary to get them all able to do this

I'd imagine that different health care providers at different scales (e.g. large hospital to small local surgery) would have different capabilities and face different challenges doing this.

**Comment by jeffallen** [comment]
The white paper describes a scheme where at the moment of testing, the patient is given an inactive code and at the moment of diagnosis the code is marked active. This can be implemented in a simple centralised way by e.g. OFSP because the website stocking these inactive and active authorisation codes need not have any other state stored with them. Even the authorisation to mark a code active could be stateless: during auth code (AC) creation, make a second code which is the auth code edit auth code (ACE). Print two labels, one with AC, one with AC and ACE. Stick AC on the app info flyer and stick ACE on the paperwork associated with the sample collection process.

**Comment by lbarman** [comment]
Sorry @davidbarnardwills, issue got buried under a ton of others. 

To paragraph Jeff (thanks for the answer ;) ): it's not a very complex part of the system, it cannot be done currently but would require some form of authorization (e.g., all health authorities have access to some app/website where they enter some credentials).

The whitepaper is blurry in that aspect because each deployment/country will probably want a different solution.

Would this answer the question?

**Comment by kugelfish42** [comment]
@lbarman operationally this could be a very hard problem as potentially thousands of persons in testing labs or medical practices need to be able to generate such authorization tokens. A single centralized service would become a single point of failure and attach which could bring down the whole system. Even in a distributed system, thousands of people would need to have the authority to generate tokens and you only need to compromise one of them to flood the system with false indications.

It might be best to use an existing identity and authentication framework, specially if medial information systems with SSO already exist in some countries.

Also in a fully federated system any auth token issues by any authority anywhere in the world need to be recognized by any server (or even client?) which might be another reason to create explicit inter-domain server-server interfaces where a server proxy certifies all the authorized IDs from its domain. If that server key is compromised, it can do a lot of harm obviously.

There are a few entities which operate widely used global identity and authorization syndication platforms, but relying on them for this service might not be in the spirit of openness and transparency.

**Comment by lbarman** [comment]
> Also in a fully federated system any auth token issues by any authority anywhere in the world need to be recognized by any server (or even client?) which might be another reason to create explicit inter-domain server-server interfaces where a server proxy certifies all the authorized IDs from its domain. If that server key is compromised, it can do a lot of harm obviously.

Absolutely; it becomes very hard when taking into account roaming / interoperability. I should have acknowledged this.

> It might be best to use an existing identity and authentication framework, specially if medial information systems with SSO already exist in some countries.

I think too that this might be our best bet :)

**Comment by pitsch** [comment]
so actually, a bad actor or prankster could just trigger a test run and the system design has (yet) no specified functionality to prevent this?

**Comment by lbarman** [comment]
Hi @pitsch; thanks for the input; what attack do you have in mind ? Can you give an example ?

**Comment by pitsch** [comment]
i might not have a full overview of the entire documentation, but besides alice and bob, there is are the actors of the testlab, the doctor and the health office involved in the testing workflow.  interestingly most tests are run as usual in medial test labs on the basis of an anonymous hash. this cryptographic truth could be the declared as the root of trust, validated by the identity check of the health office and the trustful testimony of the doctor. none of this is integrated in your documentation AFAIK so far since it would transform your decentralized design principles into a federated organisation of entities, acknowleding the fact of institutional and lawful embededdness. you need to realistically define the root of trust, which is a validated test case, which triggers the contact tracing messaging.

**Comment by lbarman** [comment]
Well the full medical infrastructure is not described, but it is abstracted as "the health authority". In practice, as you describe, it is likely to be a federated organisation of entities.

In addition, we assume this overall entity is honest; if malicious (because of an internal bad actor, e.g., a doctor who wants to tell the world Alice is infected), it can indeed do bad things, but that's our threat model. One reason for this is because patients already trust their doctor with their personal information. We could perhaps build more complex systems to avoid this, but I don't see a simple solution :)
