### ISSUE TITLE
Explanation (explainability?) of app behaviour to the use

### ISSUE THREAD

**Issue by davidbarnardwills** [DP-3T/documents#91]
Has there been any thinking about how the operation of an app based on this protocol would explain itself to the end user? and what would be the best way to simply represent what is going on in order to 
1) generate trust and confidence in the process
3) meet any obligations towards transparency
2) allow them to make sense of the result of the risk score (including all the possiblity of false positives etc) 

Visuals and multiple methods would be good, e.g. images, text and voice (for visually impared). 

Are we in the territory of profiling and automated decision making here? 
There's certainly the calculation of a risk score.

**Comment by mex2meou** [comment]
Hi @davidbarnardwills, thanks for raising this issue!

Indeed, it is very important for the app to provide some explainability to its users. 

Regarding transparency and confidence in the process, we start by the basics: making documentation and code publicly available so that the public can investigate and understand it.

I will forward your request regarding the app allowing users to make sense of the risk score with an appropriate UI to our developing teams. If you have concrete ideas about this, please post them here - I will keep this issue open.

**Comment by lbarman** [comment]
hi @davidbarnardwills, closing the issue to reduce the number of open things we need to address... This is a good idea, and also is pointed out in https://github.com/DP-3T/documents/issues/220
